### ISSUE TITLE
Konvertering af dBASE-filer

### ISSUE THREAD

**Issue by clausjuhl** [aarhusstadsarkiv/reference-files#14]
Vi skal have fundet ud af, om dBASE-filer med mere end en tabel kan konverteres med LibreCalc eller lignende. Vi skal også have set på, hvordan vi eventuelt har encoding-problemer med LibreOffice.

**Comment by ValdemarOtte** [comment]
Umiddelbart, så kan dBASE-filer ikke indeholder mere end en tabel - Se https://stackoverflow.com/questions/41094192/can-a-dbf-file-contains-more-than-one-table

Dog, så synes vi det er mærkeligt, at dBASE-filer er ofte 2-4 gange større end når det er glemt i ods formaten.

**Comment by ValdemarOtte** [comment]
Alt tyder på at der kun findes en tabel per fil.
Den primære begrundelse lægger på, at Library of Congress eller Pronom kun beskriver det som en tabel og ikke flere tabeller.
